#===========
#   ENV
#===========
[env]
EDITOR = "nvim"
MANPAGER = "nvim +Man!" # use --clean if config gets too bloated

#===========
# TOOLS
#===========

#==== neovim ====
#"npm:bash-language-server" = "latest" # TODO: comment back in this was a MISE bug
#lua-language-server = "latest" # TODO: comment back in this was a MISE bug

#==== python ====
uv = "0.9"
ruff = "0.14"
#"pipx:ty" = "latest" # TODO: comment back in... this was a MISE bug

#==== golang ====
go = "1.25"
#"go:golang.org/x/tools/gopls" = "0.20" # TODO: comment back in this was a MISE bug

#===========
# SETTINGS
#===========
[settings]
activate_aggressive = true # prefer mise binaries over system binaries
experimental = true
lockfile = true
idiomatic_version_file_enable_tools = ["python"]

